Repository wecode-bootcamp-korea/fullstack-4-React-Webucks-2, pull requests merged in 2022-03, with the labels that each got.

#3 Add: Router 파일 수정 & Mission 0 완료
  public/images/haeyunjun/coffee1.webp
  public/images/haeyunjun/coffee10.webp
  public/images/haeyunjun/coffee11.webp
  public/images/haeyunjun/coffee12.jpeg
  public/images/haeyunjun/coffee2.webp
  public/images/haeyunjun/coffee3.webp
  public/images/haeyunjun/coffee4.webp
  public/images/haeyunjun/coffee5.webp
  public/images/haeyunjun/coffee6.webp
  public/images/haeyunjun/coffee7.webp
  public/images/haeyunjun/coffee8.jpeg
  public/images/haeyunjun/coffee9.webp
  public/index.html
  public/robots.txt
  src/Router.js
  src/components/Nav/Nav.scss
  src/pages/haeyunjun/Detail/Detail.js
  src/pages/haeyunjun/Detail/Detail.scss
  src/pages/haeyunjun/List/List.js
  src/pages/haeyunjun/List/List.scss
  src/pages/haeyunjun/Login/Login.js
  src/pages/haeyunjun/Login/Login.scss
  src/pages/haeyunjun/Main/Main.js
  src/pages/haeyunjun/Main/Main.scss
  src/pages/haeyunjun/TopNav.js
Labels: Mission 0 완료

#21 'Error : detail.js에서json 파일 불러오지 못하는 오류, Router.js 오류'
  public/data/CbNitroVaCream.json
  src/pages/seulaLee/Detail/Detail.js
  src/pages/seulaLee/List/List.js
  src/pages/seulaLee/List/List.scss
Labels: Mission 0 완료, Mission 1 완료

#22 Add : Mission 1 - 사용자 입력 데이터 저장 기능 구현
  src/Router.js
  src/pages/seulaLee/Login/Login.js
  src/pages/seulaLee/Login/Login.scss
Labels: Mission 2 완료

#26 Mission 1 완료
  package-lock.json
  package.json
  public/data/haeyun/1.json
  public/data/haeyun/10.json
  public/data/haeyun/11.json
  public/data/haeyun/12.json
  public/data/haeyun/2.json
  public/data/haeyun/3.json
  public/data/haeyun/4.json
  public/data/haeyun/5.json
  public/data/haeyun/6.json
  public/data/haeyun/7.json
  public/data/haeyun/8.json
  public/data/haeyun/9.json
  public/data/haeyun/CoffeeData.json
  src/Router.js
  src/pages/haeyunjun/Detail/Detail.js
  src/pages/haeyunjun/List/CoffeeCard.js
  src/pages/haeyunjun/List/CoffeeCard.scss
  src/pages/haeyunjun/List/List.js
  src/pages/haeyunjun/List/List.scss
  src/pages/haeyunjun/List/images/coffee1.webp
  src/pages/haeyunjun/List/images/coffee10.webp
  src/pages/haeyunjun/List/images/coffee11.webp
  src/pages/haeyunjun/List/images/coffee12.jpeg
  src/pages/haeyunjun/List/images/coffee2.webp
  src/pages/haeyunjun/List/images/coffee3.webp
  src/pages/haeyunjun/List/images/coffee4.webp
  src/pages/haeyunjun/List/images/coffee5.webp
  src/pages/haeyunjun/List/images/coffee6.webp
  src/pages/haeyunjun/List/images/coffee7.webp
  src/pages/haeyunjun/List/images/coffee8.jpeg
  src/pages/haeyunjun/List/images/coffee9.webp
  src/pages/haeyunjun/Login/Login.js
  src/pages/haeyunjun/Login/Login.scss
  src/pages/haeyunjun/Login/LoginComponent.js
  src/pages/haeyunjun/components/CoffeeCard.js
  src/pages/haeyunjun/components/TopNav.js
  src/pages/haeyunjun/components/TopNav.scss
Labels: Mission 1 완료

#30 Add : Mission 3 - 커피 상세 페이지 좋아요 기능 구현
  public/index.html
  src/pages/haeyunjun/Detail/Detail.js
  src/pages/haeyunjun/Detail/Detail.scss
  src/pages/haeyunjun/Login/Login.js
  src/pages/haeyunjun/Login/Login.scss
  src/pages/haeyunjun/Login/LoginComponent.js
  src/pages/haeyunjun/components/TopNav.scss
Labels: Mission 4 완료
